P2 506 add recommended blocks to sidebar
Yoast/javascript pull request #1001
Opened 2021-01-06 19:42 UTC by increddibelly

## Summary

This PR can be summarized in the following changelog entry:

* Adds a panel to the sidebar for Recommended blocks.

## Relevant technical choices:

* this block shares most of its behavior with Required blocks, by design. Both deliver a panel to the sidebar which allows blocks to be added.
* The Innerblocks.ts file had to be renamed to Innerblocks.tsx, as we had to manipulate the React Elements in the Sidebar function.
* validation will have to change after P2-281 is merged. Recommended blocks are optional (which doesn't invalidate the parent block), but optional blocks can still be invalid.
* extended unit tests for the process function to guarantee proper parsing of recommended vs required blocks.

## Test instructions

This PR can be tested by following these steps:

change recipe.block.php to the following snippet:
```<?php // phpcs:ignore Internal.NoCodeFound ?>
{{block name="yoast/recipe" title="Recipe" category="common" }}
{{sidebar-duration name="cook-time" output=false label="Cook time" }}
{{sidebar-duration name="prep-time" output=false label="Preparation time" }}
{{sidebar-input name="yield" output=false type="number" label="Serves #" }}
<div class={{class-name}}>
	{{variable-tag-rich-text name="title" tags=[ "h1", "h2", "h3", "h4", "h5", "h6", "strong" ] placeholder="Recipe title" }}
	{{inner-blocks required-blocks=[ { "name": "core/paragraph", "option": "One" } ] recommended-blocks=[ "core/image", "core/paragraph" ] appender="button" appenderLabel="Add to recipe" }}
</div>
```
* in the monorepo/src/schema-blocks folder: `yarn install` and `yarn build`
* in the plugin: `grunt build:js`
* add a recipe to a post. 
* notice the sidebar contains required blocks and recommended blocks.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * code is hidden behind the schema blocks feature. 

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-01-26 08:28 UTC, andizer requested changes
CR done

2021-01-26 08:28 UTC, andizer commented on packages/schema-blocks/src/leaves/blocks/BlockInstructionLeaf.ts
> +		// We sometimes have a race condition here
```suggestion
		// We sometimes have a race condition here.
```

2021-01-26 08:28 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
> +			elements.push( BlockSuggestions( "Required Blocks", currentBlock, this.options.requiredBlocks ) );
But we can do this later

2021-01-26 08:28 UTC, andizer commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
>  		.map( requiredBlock => requiredBlock.name );
```suggestion
		.map( relevantBlock => relevantBlock.name );
```

2021-01-26 08:28 UTC, andizer commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
>  		.filter( requiredBlock => typeof getBlockType( requiredBlock.name ) !== "undefined" )
```suggestion
		.filter( relevantBlock => typeof getBlockType( relevantBlock.name ) !== "undefined" )
```

2021-01-26 08:28 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
> +		return (
Don't we need an elements empty check here, just to prevent rending an empty `<Fragment>` ?

2021-01-26 08:28 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
> +	 * Renders all innerblocks as react elements.
```suggestion
	 * Renders all innerblocks as react elements.
	 *
```

2021-01-26 11:18 UTC, increddibelly commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
> +export default function RequiredBlocks( sidebarTitle: string, block: BlockInstance, blocks: SuggestedBlockDefinition[] ): ReactElement {
anything worthy of a variable is automatically relevant. would anyone use irrelevantblocks in their code? 🙃

2021-01-26 13:17 UTC, andizer approved these changes
CR Done

2021-01-27 16:26 UTC, johannadevos commented
Acceptance: 🚧 

I followed the test instructions but am only seeing the Required blocks (paragraph) in the side bar. That works well, I can add it and then see OK.

Recommended blocks are absent.

2021-01-28 11:29 UTC, johannadevos commented
Acceptance: ✅ 
After the contents of `recipe.block.php` template were updated in the test instructions, I got the desired results.

2021-01-28 11:29 UTC, merged