Add full text specs for Hungarian
Yoast/javascript pull request #1011
Opened 2021-01-12 09:25 UTC by hannaw93

## Summary

This PR can be summarized in the following changelog entry:

* [yoastseo] Adds Turkish texts and specs to check the assessments functionality for Hungarian.

## Relevant technical choices:
*

## Test instructions

This PR can be tested by following these steps:
* Run yarn test and make sure all tests pass

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [x] I have added unittests to verify the code works as intended

Fixes https://yoast.atlassian.net/browse/LINGO-607

2021-01-12 16:14 UTC, iolandasequino requested changes
CR and Acceptance: 👎 
Yarn test will have to re-run after the changes to the locale

2021-01-12 16:14 UTC, iolandasequino commented on packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper1.js
> +	locale: "tr_TR",
The locale should be "hu_HU"

2021-01-13 10:29 UTC, hannaw93 commented on packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper1.js
> +	locale: "tr_TR",
Thanks, fixed!

2021-01-13 13:10 UTC, iolandasequino commented
CR & Acceptance: 👍

2021-01-13 13:12 UTC, merged