P2-252 - Date instruction for Schema blocks package
Yoast/javascript pull request #1014
Opened 2021-01-12 11:34 UTC by hansjovis

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Adds a Date block instruction for adding dates to a schema block template.

## Relevant technical choices:

* Did not end up creating a Schema instruction, since the Attribute schema instruction can be used instead.
	* The date in the Schema is a string, saved as an attribute on the block. Since the saved attribute is already in ISO-8601 format, adding a new instruction does not add anything.
* I could not get a unit test to work that would test the `edit` method of the instruction.
	* After discussing this with the team we decided to skip the test for now and [solve it later](https://yoast.atlassian.net/browse/P2-603).

## Test instructions

This PR can be tested by following these steps:

### Setting up everything for the test
* Checkout the `P2-252-Create-date-instruction` branch on `wordpress-seo`.
* Add a date instruction to the recipe **block** template:
	* Sample date instruction for adding a `publishedDate` date attribute:
	  ```
	  {{date name="publishedDate" }} 
	  ```
* Add an attribute instruction to the recipe **schema** template:
	* Sample instruction:
	  ```
	  "publishedDate": {{attribute name="publishedDate" }}
	  ```
* Build the JavaScript files, in the `schema-blocks` package as well as the Free plugin.
	* E.g. `yarn build` in the `schema-blocks` package and `grunt build:js` in the Free plugin. 

### Testing in the editor
* Create a new post.
* Add a recipe block.
* You should see a gray text with the date format (e.g. `F j, Y`) as currently configured in the site settings.
* Click on the gray text, you should see a date picker, and select a date.
* The gray text should change to the selected date.
* Save the post.

### Testing on the site itself.
* View the saved post with the recipe on the site itself.
* Check the Schema that is added to the page.
	* It should contain a graph piece for the recipe, containing the added `publishedDate` attribute.
	* This attribute's value should be the date selected in the editor, but in ISO-8601 format (e.g. `YYYY-MM-DD`).
	* Example:
	  ```json
	  {
          "@type": "Recipe",
          "@id": "http://basic.wordpress.test/sushi/#/schema/yoast-recipe-0",
          "mainEntityOfPage": {
              "@id": "http://basic.wordpress.test/sushi/#webpage"
          },
          "name": "Sushi",
          "author": {
              "@id": "http://basic.wordpress.test/#/schema/person/a00dc884baa6bd52ebacc06cfd5aab21"
          },
          "recipeInstructions": [
              {
                  "@type": "HowToStep",
                  "name": "Cook the rice.",
                  "url": "http://basic.wordpress.test/sushi/#/schema/yoast-step-0-1-0"
              }
          ],
          "recipeIngredient": [
              "Rice",
              "Salmon",
              "Seaweed"
          ],
          "publishedDate": "2021-01-21" // <-- This.
      }
	  ```

### Other date formatting
* Go to your site settings.
* Change your date format, e.g. to `Y-M-d`.
* Create a new post.
* Add a recipe block.
* Test the date instruction like before, on the editor as well as on the site itself, but see that the date format has changed to be the one configured in the site's settings.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * N/A, since this functionality is behind the Schema blocks feature flag.

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-01-13 10:11 UTC, Xyfi requested changes

2021-01-13 10:11 UTC, Xyfi commented on packages/schema-blocks/src/instructions/blocks/Date.tsx
> +	setDate( date: string, setAttributes: ( newAttributes: object ) => void ) {
I feel like this function is unnecessary since it's a simple wrapper for `setAttributes`. Also passing the `setAttributes` function to it should not be necessary because it should be accessible through `this.props`. 

I would rather see the function declaration in the `edit` function to be removed and the additional steps that that function takes to be executed in this function.

Also I would choose to make this function private, unless testability is a big deal.

2021-01-14 09:08 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/Date.tsx
> +	setDate( date: string, setAttributes: ( newAttributes: object ) => void ) {
> Also passing the `setAttributes` function to it should not be necessary because it should be accessible through this.props`.

That is not possible unfortunately, since the class is not a React component. Instead, you should see the `edit` method as a functional React component embedded in another class.

This also means that the entire state of the React component should be based around hooks. Otherwise, React can't handle the state. 

This makes extracting the `setDate` function declaration from the `edit` function complicated. The state and the state update functions should be passed as arguments, since we cannot use `this.props` or `this.setState`.

2021-01-14 10:30 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/Date.tsx
> +// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
I opted to add a type definition to the `__experimentalGetSettings` function instead.
That seemed to be the 'right' way to go about it instead of blatantly ignoring the warning TypeScript gives 😛 .

2021-01-14 10:31 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/Date.tsx
> +// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
Does not work for the tests yet, though...

2021-01-14 11:03 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/Date.tsx
> +// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
I seemed to get it working for the tests as well now.

2021-01-25 07:50 UTC, increddibelly requested changes

2021-01-25 08:10 UTC, hansjovis commented on packages/schema-blocks/package.json
> +    "react-test-renderer": "^16.12.0",
During my research in trying to get the `useState` hook to work in the tests I stumbled upon the advice that the `react-test-renderer` should be the same major version as the `react` and `react-dom` library. To avoid any conflicts in functionality.

Since the peer dependencies are React 16 and React-DOM 16 I set the test renderer to the same major version as well.

2021-01-25 14:45 UTC, andizer approved these changes
CR done

2021-01-26 15:39 UTC, increddibelly commented
Acceptance 🚫 -> date needs css

2021-01-28 10:49 UTC, hansjovis commented
I can only reproduce the issue when I replace the template with the date instruction like this:
```php
<?php // phpcs:ignore Internal.NoCodeFound ?>
{{block name="yoast/recipe" title="Recipe" category="common" }}
{{sidebar-duration name="cook-time" output=false label="Cook time" }}
{{sidebar-duration name="prep-time" output=false label="Preparation time" }}
{{sidebar-input name="yield" output=false type="number" label="Serves #" }}
{{date name="publishedDate" }}
```
Adding it to the existing template works as expected:
```php
<?php // phpcs:ignore Internal.NoCodeFound ?>
{{block name="yoast/recipe" title="Recipe" category="common" }}
{{sidebar-duration name="cook-time" output=false label="Cook time" }}
{{sidebar-duration name="prep-time" output=false label="Preparation time" }}
{{sidebar-input name="yield" output=false type="number" label="Serves #" }}
<div class={{class-name}}>
	{{variable-tag-rich-text name="title" tags=[ "h1", "h2", "h3", "h4", "h5", "h6", "strong" ] placeholder="Recipe title" }}
	{{inner-blocks required-blocks=[ { "name": "core/paragraph", "option": "Multiple" } , { "name": "core/image", "option": "One" } ] recommended-blocks=[ "core/image", "core/paragraph" ] appender="button" appenderLabel="Add to recipe" }}
    {{date name="publishedDate" }}
</div>
```
For the missing schema: make sure that the resulting schema is valid JSON, e.g. that all the comma's are correct. Else no schema for the recipe will be generated:
```js
<?php // phpcs:ignore Internal.NoCodeFound ?>
{{schema name="yoast/recipe"}}
{
	"@type": "Recipe",
	"@id": "{{block-id}}",
	"mainEntityOfPage": {
		"@id": "%%main_schema_id%%"
	},
	"image": {{inner-blocks-id allowed-blocks=[ "core/image" ] only-first=true null-when-empty=true }},
	"name": {{html name="title"}},
	"author": {
		"@id": "%%author_id%%"
	},
	"description": {{inner-blocks-html blocks={ "core/paragraph": "content" } null-when-empty=true allowed-tags=[ "h1","h2","h3","h4","h5","h6","br","a","p","b","strong","i","em" ] }},
	"cookTime": {{attribute name="cook-time" }},
	"prepTime": {{attribute name="prep-time" }},
	"recipeInstructions": {{inner-blocks allowed-blocks=[ "yoast/steps" ] only-first=true }},
	"recipeIngredient": {{inner-blocks allowed-blocks=[ "yoast/ingredients" ] only-first=true }},
	"recipeYield": {{attribute name="yield" }}, // <--- Comma here!
    "publishedDate": {{attribute name="publishedDate" }}
}
```
I will update the test instructions to reflect this.

2021-02-01 09:30 UTC, andizer commented
Acceptance almost 100%.

When inserting the recipe the field get todays date, which can be fine because I might want to publish it today. However the date won't be visible in the schema data. When changing the date to something else it will work. It also works when it is changed back to todays date.

2021-02-01 14:54 UTC, andizer commented
Acceptance 👍

2021-02-01 15:06 UTC, merged