Added readme and changelog for the @yoast/schmea-blocks package
Yoast/javascript pull request #1030
Opened 2021-01-26 08:08 UTC by Xyfi

## Summary

This PR can be summarized in the following changelog entry:

*

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

*

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-01-26 13:53 UTC, andizer requested changes
One question about the date  that is given in the changelog.

2021-01-26 13:53 UTC, andizer commented on packages/schema-blocks/CHANGELOG.md
> +## 1.1.0 Januari 11th, 2021
Is this date right? Because it lies in the past.

```suggestion
## 1.1.0 January 11th, 2021
```

2021-01-26 14:48 UTC, increddibelly commented on packages/schema-blocks/CHANGELOG.md
> +## 1.1.0 Januari 11th, 2021
1.10 was released without changelog. we're retrofitting that now :-)

2021-01-26 14:49 UTC, hansjovis commented on packages/schema-blocks/CHANGELOG.md
> +## 1.1.0 Januari 11th, 2021
1.1.0 has been released on January 11th, so this date is right.

[According to NPM we released four 'stable' versions: 1.0.0, 1.1.0, 1.1.1 and 1.2.0.](https://www.npmjs.com/package/@yoast/schema-blocks) 1.3.0 is now in the RC process. I would expect changelog items for those versions as well.

2021-01-27 08:18 UTC, hansjovis requested changes

2021-01-27 08:18 UTC, hansjovis commented on packages/schema-blocks/CHANGELOG.md
> +* Creates a new package for the Schema blocks API that is used for our schema generation.
[According to NPM we released four 'stable' versions: 1.0.0, 1.1.0, 1.1.1 and 1.2.0. 1.3.0 is now in the RC process.](https://www.npmjs.com/package/@yoast/schema-blocks) I would expect changelog items for those versions as well.

2021-02-01 08:02 UTC, merged