P2 364 block removal warnings
Yoast/javascript pull request #1040
Opened 2021-02-02 14:46 UTC by increddibelly

## Summary

This PR can be summarized in the following changelog entry:

* Adds sidebar analysis warnings explaining exactly what is 'wrong' with the user's post.

## Relevant technical choices:

* Split InnerBlocks into logic and presenter logic, it was getting too big and the number of imports was growing fast.
* Added a sidebarwarningpresenter with short methods for easy unit testing.

## Test instructions

This PR can be tested by following these steps:

* should be tested together with https://github.com/Yoast/wordpress-seo/pull/16614

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-02-03 16:10 UTC, hansjovis requested changes

2021-02-03 16:10 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +export function innerBlocksSidebar( currentBlock: BlockInstance, options: InnerBlocksInstructionOptions ): ReactElement[] {
In my opinion presenters should not be responsible for retrieving any information from the store. Presenters should only be responsible for presenting the data that it is given. It makes for a better separation of concerns.

In this case I would say that the `InnerBlocksSidebarPresenter` should get a list of warnings (strings) that it should represent.

2021-02-03 16:11 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +export function innerBlocksSidebar( currentBlock: BlockInstance, options: InnerBlocksInstructionOptions ): ReactElement[] {
However, this can be refactored at a later time.

2021-02-04 10:33 UTC, hansjovis approved these changes

2021-02-04 10:33 UTC, hansjovis commented on packages/schema-blocks/src/functions/innerBlocksHelper.ts
> +	const result: T[] = [];
Nice! 👍

2021-02-05 10:26 UTC, johannadevos commented on packages/schema-blocks/package.json
> +    "lodash": "^4.17.15"
Nice. I'm looking at the other `devDependencies`, shouldn't (some of the ) `@types` be moved up to the production `dependencies` also?

2021-02-05 10:26 UTC, johannadevos commented on packages/schema-blocks/package.json
> +}
You removed the newline at the end of the file, I don't think we want that.

2021-02-05 10:50 UTC, johannadevos commented
CR: ✅ 

But:
- [ ] Code coverage for the `SidebarWarningPresenter.ts` is at 80%, are you aware of this? 
- [ ] No unit tests for the `InnerBlocksSidebarPresenter`.

2021-02-05 10:53 UTC, increddibelly commented on packages/schema-blocks/package.json
> +    "lodash": "^4.17.15"
@types help vscode do typevalidation in typescript, so that's dev only.

2021-02-05 10:56 UTC, johannadevos commented on packages/schema-blocks/package.json
> +    "lodash": "^4.17.15"
Ah 💡

2021-02-08 09:54 UTC, johannadevos commented
Acceptance: 🚫 

I added a few `console.log` statements. They tell me that `warning` is `null`, therefore I never enter the conditional in which `createWarningList` is called.

<img width="879" alt="Screenshot 2021-02-08 at 10 51 29" src="https://user-images.githubusercontent.com/20280513/107203342-9ad09200-69fb-11eb-8df3-65c110f31004.png">

This is the output of the log statements: 

<img width="961" alt="Screenshot 2021-02-08 at 10 52 33" src="https://user-images.githubusercontent.com/20280513/107203455-c18ec880-69fb-11eb-8563-a9fdcab9dbdd.png">

I followed these steps:
* Created a new post.
* Added a recipe block.

These are the contents of my `recipe.block.php`:

```
<?php // phpcs:ignore Internal.NoCodeFound ?>
{{block name="yoast/recipe" title="Recipe" category="common" }}
{{sidebar-duration name="cook-time" output=false label="Cook time" }}
{{sidebar-duration name="prep-time" output=false label="Preparation time" }}
{{sidebar-input name="yield" output=false type="number" label="Serves #" }}
<div class={{class-name}}>
	{{variable-tag-rich-text name="title" tags=[ "h1", "h2", "h3", "h4", "h5", "h6", "strong" ] placeholder="Recipe title" }}
	{{inner-blocks allowed-blocks=[ "core/image", "core/paragraph" ] required-blocks=[ { "name": "yoast/steps", "option": "1" } , { "name": "yoast/ingredients", "option": "1" } ] recommended-blocks=[ {"name": "core/image" }, { "name": "core/paragraph" }] appender="button" appenderLabel="Add to recipe" }}
</div>
```

2021-02-08 13:56 UTC, increddibelly commented
@johannadevos could you please check with the Redux DevTools plugin if you see validations in the store?
you'd expect a tree similar to this:
`State > root > schemaBlocks > validations > [clientId] : BlockValidationResult`
![image](https://user-images.githubusercontent.com/3604126/107229092-af258680-6a1d-11eb-8512-d902d9fef752.png)

2021-02-09 08:53 UTC, johannadevos commented
I got a little further in investigating why it isn't working for me.

`getValidationResult` returns `null`, therefore `getWarnings` returns `null`, and therefore I don't enter this conditional:

<img width="396" alt="Screenshot 2021-02-09 at 09 51 31" src="https://user-images.githubusercontent.com/20280513/107338932-653fad80-6abc-11eb-8c72-75d1b4085364.png">

Why does `getValidationResult` return `null`?
Because `! store.validations` is `true` for me.

<img width="292" alt="Screenshot 2021-02-09 at 09 52 06" src="https://user-images.githubusercontent.com/20280513/107339008-7983aa80-6abc-11eb-82fc-b4d3014a29e4.png">

<img width="494" alt="Screenshot 2021-02-09 at 09 52 36" src="https://user-images.githubusercontent.com/20280513/107339082-8bfde400-6abc-11eb-810c-7894015fea8c.png">

Apparently something goes wrong in getting the `store`.

<img width="856" alt="Screenshot 2021-02-09 at 09 53 09" src="https://user-images.githubusercontent.com/20280513/107339138-a041e100-6abc-11eb-836e-b4e50263339a.png">

2021-02-09 14:13 UTC, johannadevos commented
Acceptance: ✅ 

- [x] I see the analysis in the sidebar and it matches the designs.

<img width="224" alt="Screenshot 2021-02-09 at 15 00 38" src="https://user-images.githubusercontent.com/20280513/107374157-941f4900-6ae7-11eb-9086-a625aedb386a.png">

- [x] When I add one of the two missing required blocks, that block warning disappears from the sidebar.
- [x] When I inspect the Schema output, the `JobPosting ` graph piece is absent.
- [x] When I add the second (last) of the two missing required blocks, the analysis turns green:

<img width="216" alt="Screenshot 2021-02-09 at 15 02 46" src="https://user-images.githubusercontent.com/20280513/107374435-dfd1f280-6ae7-11eb-8bc7-42ab06e937e6.png">
  
- [x] The `JobPosting` graph piece is now present in the Schema output.
- [x] I saw it work in both Free and Premium.

For Free I used this `recipe.block.php` template:

```
<?php // phpcs:ignore Internal.NoCodeFound ?>
{{block name="yoast/recipe" title="Recipe" category="common" }}
{{sidebar-duration name="cook-time" output=false label="Cook time" }}
{{sidebar-duration name="prep-time" output=false label="Preparation time" }}
{{sidebar-input name="yield" output=false type="number" label="Serves #" }}
<div class={{class-name}}>
	{{variable-tag-rich-text name="title" tags=[ "h1", "h2", "h3", "h4", "h5", "h6", "strong" ] placeholder="Recipe title" }}
	{{inner-blocks allowed-blocks=[ "core/image", "core/paragraph" ] required-blocks=[ { "name": "yoast/steps", "option": "1" } , { "name": "yoast/ingredients", "option": "1" } ] recommended-blocks=[ {"name": "core/image" }, { "name": "core/paragraph" }] appender="button" appenderLabel="Add to recipe" }}
</div>
```

For Premium I used this `job-posting.block.php` template:

```
<?php
/**
 * Job posting block schema template.
 *
 * @package Yoast\WP\SEO\Schema_Templates
 */

/* translators: %1$s expands to Yoast */
$yoast_seo_block_title = sprintf( __( '%1$s Job posting', 'wordpress-seo-premium' ), 'Yoast' );
?>
{{block name="yoast/job-posting" title="<?php echo esc_attr( $yoast_seo_block_title ); ?>" keywords=[ "SEO", "Schema"] description="<?php esc_attr_e( 'Create a Job Posting in an SEO-friendly way. You can only use one Job Posting block per post.', 'wordpress-seo-premium' ); ?>" icon="portfolio" category="yoast-structured-data-blocks" }}
{{sidebar-select name="type" output=false label="<?php esc_attr_e( 'Employment type', 'wordpress-seo-premium' ); ?>" options={ "<?php esc_attr_e( 'Full time', 'wordpress-seo-premium' ); ?>": "FULL_TIME", "<?php esc_attr_e( 'Part time', 'wordpress-seo-premium' ); ?>": "PART_TIME" } multiple=true }}
{{sidebar-input name="minimum-hours" output=false type="number" label="<?php esc_attr_e( 'Minimum hours', 'wordpress-seo-premium' ); ?>" }}
{{sidebar-input name="maximum-hours" output=false type="number" label="<?php esc_attr_e( 'Maximum hours', 'wordpress-seo-premium' ); ?>" }}
<div class={{class-name}}>
	{{variable-tag-rich-text name="title" tags=[ "h1", "h2", "h3", "h4", "h5", "h6", "strong" ] placeholder="<?php esc_attr_e( 'Job title', 'wordpress-seo-premium' ); ?>" }}
	{{inner-blocks appender="button" required-blocks=[ { "name": "yoast/job-description", "option": "1" } , { "name": "yoast/job-title", "option": "1" } ] recommended-blocks=[ "yoast/job-expiration" ] appenderLabel="<?php esc_attr_e( 'Add to job', 'wordpress-seo-premium' ); ?>" }}
</div>
```

2021-02-09 14:31 UTC, merged