P2 681 add inherit sidebar block
Yoast/javascript pull request #1066
Opened 2021-02-16 15:25 UTC by increddibelly

## Summary

This PR can be summarized in the following changelog entry:

* [@yoast/schema-blocks] Adds Inherit-Sidebar instruction.

## Relevant technical choices:

* added an inherit-sidebar instruction which allows subblocks to show their parents' sidebar when the subblock is selected.
* 
## Test instructions

This PR can be tested by following these steps:

* add `{{ inherit-sidebar }}` to the template that resides in an innerblock of another template; e.g. add this to the `steps` block template of the `yoast/recipe` block template. 
* add the template in a new post; open the sidebar.
* navigate between the innerblock and parent block; notice how the block name (top right) changes to indicate the current block, but the sidebar for the parent block remains.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-02-16 16:01 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/InheritSidebar.tsx
> +				const parentBlockInstruction = Instruction.getBlock( parentBlock.name );
trying to get the registered instruction with its options from the registry; this does not work as expected.

2021-02-18 12:55 UTC, increddibelly commented on packages/schema-blocks/src/core/Instruction.ts
> +	static getBlock<I extends typeof Instruction>( this: I, name: string ): InstructionClass<I["prototype"]> {
unused method - removed.

2021-02-18 12:58 UTC, increddibelly commented on packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
> +				const output = instruction.sidebar( props, index );
I removed the intermediate variables

2021-02-18 13:08 UTC, increddibelly commented on packages/schema-blocks/src/functions/gutenberg/block.ts
> + * @returns {BEP} The BlockEditProps.
BlockEditProps*

2021-02-18 13:10 UTC, andizer requested changes
CR done

2021-02-18 13:10 UTC, andizer commented on packages/schema-blocks/src/functions/gutenberg/sidebar.ts
> + * Opens the given sidebar unless the given sidebar or another sidebar is already open.
Not catched by the linter, but I would love to see a newline after this.

```suggestion
 * Opens the given sidebar unless the given sidebar or another sidebar is already open.
 *
```

2021-02-18 13:10 UTC, andizer commented on packages/schema-blocks/src/core/blocks/BlockInstruction.ts
> +	 * @returns {ReactElement | string} The sidebar element to render.
It now returns a ReactElement right? I think you can remove the `| string` part?
```suggestion
	 * @returns {ReactElement} The sidebar element to render.
```

2021-02-18 13:10 UTC, andizer commented on packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
> +				return output;
`output` is returned immediately after its declaration, I'd just return the result of the function call without storing it to a variable
```suggestion
				return instruction.sidebar( props, index );
```

2021-02-18 13:10 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/InheritSidebar.tsx
> +	protected value( props: RenderSaveProps | RenderEditProps ): string {
This methods isn't used? Also the `BlockInstruction` doesn't seem to have a `value` method. I would remove it.

2021-02-18 13:22 UTC, increddibelly commented on packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
> +				return output;
the entire function is now a oneliner.

2021-02-18 13:22 UTC, increddibelly commented on packages/schema-blocks/src/core/blocks/BlockInstruction.ts
> +	 * @returns {ReactElement | string} The sidebar element to render.
this breaks inherited blocks that DO return a string. so, not for now, unfortunately.

2021-02-18 13:30 UTC, increddibelly commented on packages/schema-blocks/src/functions/gutenberg/sidebar.ts
> +	if ( ( force || ! isEditorSidebarOpened ) && ( activeGeneralSidebarName !== sidebarName ) ) {
indeed. removed the double negation.

2021-02-18 13:30 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/Block.tsx
>  	sidebar( props: RenderEditProps ): ReactElement {
ooh, will have a look!

2021-02-22 09:58 UTC, igorschoester commented
Please rebase this to where it needs to go. The `release/15.9` branch is no longer valid, it has been released already.

2021-02-23 08:53 UTC, andizer approved these changes
CR 👍

2021-02-24 15:08 UTC, hansjovis commented
Acceptance test: ✅

2021-02-24 15:08 UTC, merged