Fixes analysis for schema blocks.
Yoast/javascript pull request #1071
Opened 2021-02-18 12:11 UTC by hansjovis

## Summary

This PR can be summarized in the following changelog entry:

* [@yoast/schema-blocks] Fixes a bug where not all block issues were logged in the schema analysis in the block sidebar.
* [@yoast/schema-blocks] Improves the logger with colors and the ability to group log statements.
* [@yoast/schema-blocks] Adds a `required` property to the `VariationPicker` block instruction. If this is set to `true`, the block should have a variation selected to be considered valid.

## Relevant technical choices:

* I improved the logger to be able to get a better overview of the validation results.
	* Now with colors!
	* And the ability to group logging statements.
* I added named constructors for the `BlockValidationResult`:
  ```ts
  BlockValidationResult.Valid( blockInstance );
  ```
  is a bit more readable than
  ```ts
  new BlockValidationResult( blockInstance.clientId, blockInstance.name, BlockValidation.Valid );
  ```

## Test instructions

This PR can be tested by following these steps:

* Companion PR of [WIP].

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * N/A: behind a feature flag.

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-02-19 13:28 UTC, increddibelly requested changes
couple of issues; note the spelling of `descendant` if we're not going for `Children`.

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +			console.log( `%c ${ LogLevel[ level ] }:`, `color: ${ color };`, ...input );
```suggestion
			console.log( `%c ${ LogLevel[ level ] }:`, `color: ${ LogColor[ level ] };`, ...input );
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
```suggestion

const logColor: Record<LogLevel, string> = { 
   LogLevel.NONE => "black",
   LogLevel.ERROR => "red", 
   LogLevel.WARNING => "darkorange",
   LogLevel.INFO => "blue",
   LogLevel.DEBUG => "darkorchid",
};   
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +	protected writeLog( level: LogLevel, color: string, ...input: unknown[] ): void {
```suggestion
	protected writeLog( level: LogLevel, ...input: unknown[] ): void {
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +	 * @param color The color of the message label.
as a matter of separation of concerns: when you're logging at a certain level, you don't care what it looks like, you just tell "the system" there's a debug message coming in. the actual logger should deal with formatting.

This is absolutely a minor thing, but I think it is very important to get into the healthy habit of getting it absolutely right.

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +		this.writeLog( LogLevel.DEBUG, "darkorchid", ...input );
```suggestion
		this.writeLog( LogLevel.DEBUG, ...input );
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +		this.writeLog( LogLevel.INFO, "blue", ...input );
```suggestion
		this.writeLog( LogLevel.INFO, ...input );
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +		this.writeLog( LogLevel.WARNING, "darkorange", ...input );
```suggestion
		this.writeLog( LogLevel.WARNING, ...input );
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +		this.writeLog( LogLevel.ERROR, "red", ...input );
```suggestion
		this.writeLog( LogLevel.ERROR, ...input );
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +	const messageData: analysisIssue[] = getAllDescendentIssues( validation )
```suggestion
	const messageData: analysisIssue[] = getAllDescendantIssues( validation )
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +		results = results.concat( getAllDescendentIssues( issue ) );
```suggestion
		results = results.concat( getAllDescendantIssues( issue ) );
```

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +function getAllDescendentIssues( validation: BlockValidationResult ): BlockValidationResult[] {
```suggestion
function getAllChildIssues( validation: BlockValidationResult ): BlockValidationResult[] {
```
descendAnt of child, de laatste is makkelijker typen :-)

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/ClassName.ts
> +	 * Always add the "yoast-inner-container" class
❤️

2021-02-19 13:28 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
> +	return blockInstance.innerBlocks && blockInstance.innerBlocks.length > 0;
how is having innerblocks a sign of having variations? at least one of the innerblocks must implement the VariationImplementation interface. (not entirely sure about that name)

```suggestion
	return blockInstance.innerBlocks && blockinstance.innerBlocks.some( block => block instanceof VariationImplementation );
```

2021-02-19 13:33 UTC, increddibelly commented on packages/schema-blocks/src/functions/logger.ts
> +	startGroup( label: string, level = LogLevel.DEBUG ): void {
these are on the console logger but not on the Logger interface. Miss Liskov would be sad.
since these are awesome, I think the interface should get these too ;-)

2021-02-19 13:35 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/Block.tsx
> +				"is-yoast-schema-block": {
hebben we hiermee afgedekt dat al onze blokken magisch het magische attribute krijgen? 👍 m.a.w. ik wil niet dat alle subblokken code moeten toevoegen zodat ze correct herkend worden.

2021-02-19 13:36 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/ClassName.ts
> +	save(): "yoast-inner-container" {
```suggestion
	save(): string {
```

2021-02-23 12:25 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
> +	return blockInstance.innerBlocks && blockInstance.innerBlocks.length > 0;
I can't seem to find a way to tell whether an inner block has been added as a variation or not 😕 .

When a variation has been picked, the inner blocks are replaced with the blocks in the variation.

2021-02-23 12:31 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/Block.tsx
> +				"is-yoast-schema-block": {
Ja. Als in: ieder block schema template (ook van de subblokken) heeft een instantie van deze instructie nodig om als blok herkend te worden.

2021-02-23 12:39 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +function getAllDescendentIssues( validation: BlockValidationResult ): BlockValidationResult[] {
Bij 'Child' denk ik altijd aan directe kinderen van iets. Ik heb uiteindelijk voor 'descendant' gekozen, sinds dat de lading beter dekt.

2021-02-25 12:41 UTC, johannadevos commented on packages/schema-blocks/src/functions/logger.ts
> +	 * @param color The color of the message label.
Resolved in https://github.com/Yoast/javascript/pull/1071/commits/32ee42b39af0bbe4c059d8e5e3142a25a69edc00

2021-02-25 12:44 UTC, johannadevos commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +function getAllDescendentIssues( validation: BlockValidationResult ): BlockValidationResult[] {
Fixed in https://github.com/Yoast/javascript/pull/1071/commits/7748eede442f084c87136bfbd3efdd42e4311a60

2021-02-25 12:46 UTC, johannadevos commented on packages/schema-blocks/src/functions/logger.ts
> +	startGroup( label: string, level = LogLevel.DEBUG ): void {
Fixed in https://github.com/Yoast/javascript/pull/1071/commits/634f82680e42e198fffaede6addaf5851adebd65

2021-02-25 12:57 UTC, johannadevos commented
CR: ✅ 

The comments from the previous CR have been implemented.

2021-03-01 10:42 UTC, andizer commented
Acceptance 👍

2021-03-15 14:49 UTC, merged