Add checkbox component
Yoast/javascript pull request #1078
Opened 2021-02-24 14:20 UTC by igorschoester

## Summary

This PR can be summarized in the following changelog entry:

* [@yoast/components] Updates the `Checkbox` component to the newer style. Now wrapped in a `FieldGroup`.

## Relevant technical choices:

* Removing the old style checkbox (I don't see it being used), the props/usage remains the same 
* Using the field group as wrapper. This is suboptimal because: 
   * the BEM `__checkbox` should be a child of the field group
    * the field group is really more a fieldset, but then this component can only be singular

## Test instructions

This PR can be tested by following these steps:

* Test with Free PR.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Partially fixes https://yoast.atlassian.net/browse/P1-301

2021-03-01 15:16 UTC, JoseeWouters requested changes
Please create a technical debt issue for the use of `useCallback` and one minor change for a comment.

2021-03-01 15:16 UTC, JoseeWouters commented on packages/components/src/checkbox/Checkbox.js
> + * Represents the input type checkbox with a label. Optionally a FieldGroup.
Please remove `optionally a fieldgroup` or make it optional.

2021-03-03 08:44 UTC, JoseeWouters approved these changes
CR 👍

2021-03-03 14:03 UTC, marijnyoast commented
Acceptance 👍🏻

2021-03-03 14:03 UTC, merged