Show an orange bullet in the sidebar analysis when a recommended block is removed
Yoast/javascript pull request #1116
Opened 2021-03-23 14:57 UTC by johannadevos

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Adds an orange bullet to the `Analysis` in the side bar when a recommended block is removed.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

* Add the Yoast Job Posting block.
* See that there are no orange bullets in the `Analysis` in the side bar, because all the recommended blocks are present upon initialization.
* Remove a recommended block, for example the 'Requirements'.
* See an orange bullet and the text: "The 'Requirements' block is recommended but missing.":
    <img width="175" alt="Screenshot 2021-03-23 at 15 21 24" src="https://user-images.githubusercontent.com/20280513/112161436-70bde280-8beb-11eb-99d3-1ebb1f4b9c46.png">

* See that the Requirements block is greyed out and can be added:
    <img width="202" alt="Screenshot 2021-03-23 at 15 21 49" src="https://user-images.githubusercontent.com/20280513/112161492-7fa49500-8beb-11eb-9845-8779a951e405.png">

* Remove another recommended block to see that it also works when multiple recommended blocks are missing.
* Remove a required block and see the same behavior as for a recommended block, except that the bullet is red rather than orange.
* Resolve all the issues with regard to the required blocks (make sure they're present and have content).
* You should see no red bullet in the sidebar analysis.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes https://yoast.atlassian.net/browse/P2-706

2021-03-26 12:32 UTC, increddibelly commented on packages/schema-blocks/src/core/validation/BlockValidationResult.ts
> +export enum BlockType {
Blocks hebben al een type; "yoast/job-posting" bijvoorbeeld. Kunnen we een meer beschrijvende naam verzinnen? 
```suggestion
export enum BlockConstraint {
```

2021-03-26 12:33 UTC, increddibelly commented on packages/schema-blocks/src/core/validation/BlockValidationResult.ts
> +		this.blockType = blockType;
```suggestion
		this.constraint= blockConstraint; // etc
```

2021-03-26 12:54 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +	const requiredIssues = issues.filter( issue => {
issues zijn altijd ongewenst toch? nooit required.
```suggestion
	const requiredBlockValidations = issues.filter( issue => {
```

2021-03-26 12:55 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +			status: issue.blockType,
```suggestion
			constraint: issue.blockType,
```

2021-03-26 12:57 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +					validationResults.push( new BlockValidationResult( block.clientId, blockName, BlockValidation.TooMany, BlockType.Unknown ) );
waarom Unknown? dat is toch ook blockType omdat je alles voor blockType checkt?

2021-03-26 12:57 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +			validations.push( new BlockValidationResult( block.clientId, block.name, BlockValidation.Unknown, BlockType.Unknown ) );
waarom unknown?

2021-03-26 13:33 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +	// Find all required block types that do not occur in existingRequiredBlocks.
op basis van het blocktype hebben we nu twee keer hetzelfde blok code. 

Dan moet imho de onderliggende code slimmer worden zodat daar onderscheid wordt gemaakt op de constraint. Zullen we daar een nieuw ticket voor maken gezien de tijd?

2021-03-26 13:39 UTC, increddibelly requested changes
zie opmerkingen; het zou nog zeer waardevol zijn om [dit deel](https://github.com/Yoast/javascript/pull/1116/files#diff-e0c9f6e4a0b893aa45a2900ad969e980760b7594de79e74f5bc0382fd5303833R113) over te dragen aan de onderliggende functie dwz dat daar de splitsing op recommended / required wordt gemaakt, maar alleen als het in een uur of twee kost.

2021-03-26 14:05 UTC, johannadevos commented on packages/schema-blocks/src/core/validation/BlockValidationResult.ts
> +export enum BlockType {
`"yoast/job-posting"` is technisch gezien de `name` 😉 . Maar ik zie je punt - wat vind je van `BlockPresence`?

2021-03-26 14:49 UTC, johannadevos commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +	const requiredIssues = issues.filter( issue => {
I renamed it to `requiredBlockIssues`. Since it's not the issues that are required, but the blocks.

2021-03-26 14:57 UTC, johannadevos commented on packages/schema-blocks/src/core/validation/BlockValidationResult.ts
> +export enum BlockType {
Conclusie: hernoemd naar `BlockPresence`.

2021-03-26 15:01 UTC, johannadevos commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +			status: issue.blockType,
Done: renamed to `presence`.

2021-03-26 16:15 UTC, johannadevos commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +					validationResults.push( new BlockValidationResult( block.clientId, blockName, BlockValidation.TooMany, BlockType.Unknown ) );
Gefixt in https://github.com/Yoast/javascript/pull/1116/commits/61804b62d22ec9f55c140195d1922ecf8f3a1202.
`blockType` (nu `blockPresence`) werd eerst nog niet meegegeven omdat deze check überhaupt alleen op required blocks werd toegepast. Dat heb ik nu ook rechtgezet.

2021-03-26 16:18 UTC, johannadevos commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +			validations.push( new BlockValidationResult( block.clientId, block.name, BlockValidation.Unknown, BlockType.Unknown ) );
Je komt in deze conditional als het block überhaupt niet geregistreerd is. Dan is het al helemaal niet bekend of hij required/recommended/optional is.

2021-03-29 11:23 UTC, johannadevos commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +	// Find all required block types that do not occur in existingRequiredBlocks.
Uitgesplitst naar https://yoast.atlassian.net/browse/P2-815.

2021-03-29 12:10 UTC, andizer reviewed
CR done

2021-03-29 12:10 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +		.replace( "{presence}", __( issue.presence, "wpseo-schema-blocks" ) );
Hmm, this will cause merge conflicts with #1127 where this logic (`replaceVariables`) has been removed.

Also please not that dynamic arguments for translations aren't translatable. The potfile builder will take `issue.presence` as value to translate.

2021-03-29 12:10 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +			text: __( "Not all required blocks have been completed! No " + issues[ 0 ].parent +
This logic has also been changed in #1127

2021-03-29 12:10 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +		return { text: replaceVariables( msg ), color: ( msg.presence === BlockPresence.Recommended ? "orange" : "red" ) } as sidebarWarning;
Tip: I would make this more readable by adding newlines. Especially the conditional makes this all hard to read/process

2021-03-29 12:31 UTC, johannadevos commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +		.replace( "{presence}", __( issue.presence, "wpseo-schema-blocks" ) );
Good to know!

2021-03-29 12:32 UTC, johannadevos commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +		return { text: replaceVariables( msg ), color: ( msg.presence === BlockPresence.Recommended ? "orange" : "red" ) } as sidebarWarning;
Good point. But I believe this code has been changed in #1127 anyway.

2021-03-29 12:51 UTC, johannadevos commented
I'm merging this PR with the blessing of the other devs in the team.

It has already been acceptance tested in a demo with @dariaknl.

The comments from @andizer's CR all relate to conflicts with #1127. We will resolve those conflicts after this PR has been merged to `develop`.

2021-03-29 12:51 UTC, merged