P1 345 woo shopping data in google preview
Yoast/javascript pull request #1118
Opened 2021-03-24 15:02 UTC by marijnyoast

## Summary

This PR can be summarized in the following changelog entry:

* [@yoast/search-metadata-previews] When product data like rating, number of reviews, price or availability is provided, it is now shown in the Google Preview.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

* Please follow the test instructions in the corresponding branch / version of WP SEO for WooCommerce

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * Search metadata preview

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [X] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes P1-345

2021-03-31 10:02 UTC, igorschoester requested changes
CR 🏗️

2021-04-01 12:51 UTC, marijnyoast commented on packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
> +			{ ( shoppingData.reviewCount > 0 ) ? <StarRating rating={ shoppingData.rating } /> : "" }
It is because I wanted to target the 3 spans without the StarRating, so that I could set color and a margin-left. This because I disliked an inline style on StarRating. But that solution is cleaner indeed.

2021-04-06 10:03 UTC, marijnyoast commented on packages/components/src/star-rating/StarRating.js
> +	rating: PropTypes.number.isRequired,
`range.between` doesn't (standard) exist. So I did a comment and added a manual check within the component.

2021-04-06 10:05 UTC, marijnyoast commented on packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
> +	shoppingData: PropTypes.object.isRequired,
Agree, added a shape.

2021-04-06 10:11 UTC, marijnyoast commented on packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
> +		if ( mode === MODE_DESKTOP && shoppingData !== null ) {
`shoppingData was` `null` when not on a product page. Since we now default to an empty object in the reducer, the check is changed to that. The whole shopping part shouldn't be rendered when the page isn't about a project, that's the 'why' for that if-statement.

2021-04-07 08:44 UTC, igorschoester requested changes
CR 🏗️

2021-04-07 08:44 UTC, igorschoester commented on packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
> +	/* Translators: %s expands to the actual rating. */
```suggestion
	/* Translators: %s expands to the review count. */
```

2021-04-07 08:44 UTC, igorschoester commented on packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
> +	/* Translators: %s expands to the actual rating. */
```suggestion
	/* Translators: %s expands to the actual rating, e.g. 8/10. */
```

2021-04-07 08:44 UTC, igorschoester commented on packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
> +			return null;
A couple of things:
- You can not compare an object to an empty different object. It compares the memory address and thus will never be the same. You can work around this by checking if there are any values for example.
- You can early return on the shoppingData check so you don't have to indent for all the rest. This improves readability of your code.
- You are missing a return for when the shoppingData is empty, that will be `undefined` instead of `null` in your current code. That is not a problem in behavior, but it is not correct.

```suggestion
		if ( Object.values( shoppingData ).length === 0 ) {
			return null;
		}
	
		if ( mode === MODE_DESKTOP ) {
			return (
				<ProductDataDesktop
					shoppingData={ shoppingData }
				/>
			);
		}
	
		if ( mode === MODE_MOBILE ) {
			return (
				<ProductDataMobile
					shoppingData={ shoppingData }
				/>
			);
		}
	
		return null;
```

2021-04-07 09:03 UTC, igorschoester approved these changes
CR 👍

2021-04-12 08:33 UTC, JoseeWouters commented
Acceptance 👍

2021-04-12 08:35 UTC, merged