P2-704 Same Post and Job titles do not trigger red analysis
Yoast/javascript pull request #1120
Opened 2021-03-25 09:18 UTC by hansjovis

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Reworks the imports and exports of the schema blocks package.

## Relevant technical choices:

* Decided together with @increddibelly to rework the imports and exports.
* Reworked the warning messages in the sidebar.
	* Now gets the warnings from the `BlockValidationResult`s itself, rather than a separate result -> warning map.

## Test instructions

This PR can be tested by following these steps:

* Test this together with [PR on Premium].

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
	* See PR in Premium.

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-03-26 14:36 UTC, increddibelly requested changes
only a few comments for minor improvements.

also, /src/functions/blocks/index.ts is an empty file, please remove

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +import { RequiredBlocks as BlockSuggestions } from "../../blocks/BlockSuggestions";
why the rename?

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/index.ts
> +import { validateInnerBlocks as getInvalidInnerBlocks } from "./innerBlocksValid";
why the rename?
```suggestion
import { validateInnerBlocks } from "./innerBlocksValid";
```

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
>  import isValidResult from "./isValidResult";
there's still a default export remaining here.

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/SidebarSelect.ts
>  // Internal imports.
```suggestion
```

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/index.ts
> +export { VariableTagRichText };
why import the rest if we're not exporting them?

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/src/instructions/schema/index.ts
> +// Need to export something for the side-effects of the imports to work...
dank voor dit comment! 
kunnen we de side effects expliciet maken / aanroepen?

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/tests/functions/BlocksHelper.test.ts
> +import { removeBlock, restoreBlock, getBlockType, getHumanReadableBlockName } from "../../src/functions/BlockHelper";
rename the file from BlocksHelper.test.ts to BlockHelper.test.ts (singular)

2021-03-26 14:36 UTC, increddibelly commented on packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
> +import getWarnings, { createAnalysisMessages } from "../../../src/functions/presenters/SidebarWarningPresenter";
can we un-default export the getWarnings?

2021-03-29 10:32 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/index.ts
> +export { VariableTagRichText };
For the `BlockInstruction.register` side effects.

Without them the block instructions are not registered.

2021-03-29 10:32 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/index.ts
> +export { VariableTagRichText };
But yes, I will export them all.

2021-03-29 15:05 UTC, hansjovis commented
Closed in favour of https://github.com/Yoast/javascript/pull/1129.

2021-03-29 15:05 UTC, closed without merging