Only output Schema when the checks for required blocks are OK
Yoast/javascript pull request #1124
Opened 2021-03-26 13:41 UTC by johannadevos

## Summary

This PR can be summarized in the following changelog entry:

* [@yoast/schema-blocks] Fixes a bug where Schema output would still be generated if all the required blocks had been valid before, even if they were no longer valid now.
* [@yoast/schema-blocks] Fixes a bug where Schema output would be generated even when no variation had been picked for the Location block.

## Relevant technical choices:

* If the Job Posting block overall isn't valid (`validation.result > BlockValidation.Valid`), we should dispatch a `null` Schema output to the store, to overwrite the Schema output that was potentially stored there before. 
* The Job location block template has multiple instructions that are validated. Therefore, these results should be combined in an 'overall' validation result by using `validateMany`. In order to do so, we first need to collect these results and flatten them into a list using `getAllDescendantIssues`.

## Test instructions

This PR can be tested by following these steps:

**Test with required blocks**
* Add a Job Posting block to your post. Don't fill in anything.
* Publish the post, inspect the Schema output, and see that the `JobPosting` graph piece is **absent**.
* Fill in the title and description, but don't choose a location in the location picker.
    * Move the focus to another block to make sure the validations are executed (should be fixed in https://yoast.atlassian.net/browse/P2-780).
    * Update the post, see that the `JobPosting` graph piece is still **absent**.
* Choose a location in the location picker (preferably the remote location, because that one is already filled in).
    * Move the focus to another block to make sure the validations are executed.
    * Update the post, see that the `JobPosting` graph piece is now **present**.
* There is a known bug: if you delete the text in the remote location, the `JobPosting` grape piece will stay present but it should be absent. This is due to https://yoast.atlassian.net/browse/P2-807. 
* Empty the title and/or description (don't remove them).
    * Move the focus to another block to make sure the validations are executed.
    * Update the post, see that the `JobPosting` graph piece is now **absent**.

**Test with recommended blocks**
* To do.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes https://yoast.atlassian.net/browse/P2-695

2021-03-26 13:48 UTC, increddibelly requested changes
even de import toevoegen aan index.ts, zie comment bij `SidebarWarningPresenter`

2021-03-26 13:48 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +import { getAllDescendantIssues } from "../validators/getAllDescendantIssues";
mooier om in `validators/index.ts` deze functie te importeren en exporteren, zodat je hier
```suggestion
import { getAllDescendantIssues } from "../validators";
```
kunt doen

2021-03-26 13:48 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/getAllDescendantIssues.ts
> +import { BlockValidationResult } from "../../core/validation";
zie comment op `SidebarWarningPresenter`, dit is mooier.

2021-03-26 14:00 UTC, johannadevos commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> +import { getAllDescendantIssues } from "../validators/getAllDescendantIssues";
Done

2021-04-01 14:36 UTC, increddibelly approved these changes

2021-04-06 07:59 UTC, andizer commented
Acceptance 👍

2021-04-06 07:59 UTC, merged