First iteration of index.ts exports.
Yoast/javascript pull request #1127
Opened 2021-03-29 09:27 UTC by hansjovis

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Adds the `RenderEditProps` and `RenderSaveProps` as package exports.

## Relevant technical choices:

* Branched from https://github.com/Yoast/javascript/pull/1120, please merge that one first!
	* Only change between that branch and this one is this commit: https://github.com/Yoast/javascript/commit/9b53b60919277ac2fd84a8cf1448807dd627a1b1

## Test instructions

This PR can be tested by following these steps:

* Companion PR of https://github.com/Yoast/wordpress-seo-premium/pull/3266. Test this PR together with that PR (it contains the test instructions)

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-03-29 11:50 UTC, andizer requested changes
CR done

2021-03-29 11:50 UTC, andizer commented on packages/schema-blocks/src/core/validation/BlockValidationResult.ts
> +			sprintf( __( "The '%s' block is required but missing.", "yoast-schema-blocks" ), name ),
Translator comment is missing, such comment would make it easier for translators to understand what is going on.

2021-03-29 11:50 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
> -		.replace( "{child}", __( issue.name, "wpseo-schema-blocks" ) )
Love the removal of this, just  because it's better to prevent having dynamical translations :)

2021-03-29 11:50 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
> +				{ ...elements}
Is there a reason for the space removal?

2021-03-29 15:14 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
> +				{ ...elements}
This happened [through the merge of the branch in which the imports/exports were changed drastically](https://github.com/Yoast/javascript/pull/1127/commits/5595b52998de2e1f65dc26720caa70f523b3a79d#diff-bce3682bcac8b2828dbbcb9b7f12817fc2f0ee7745017a0eb1bcf24bd621f93dR48).

Since I am going to create a new branch for this issue, without these changed imports/exports, this comment is not applicable anymore.

2021-03-30 08:25 UTC, hansjovis commented
Closed in favour of https://github.com/Yoast/javascript/pull/1132

2021-03-30 08:25 UTC, closed without merging