Connected Redux store with React to make sure the components update whenever the store changes.
Yoast/javascript pull request #1136
Opened 2021-03-31 12:31 UTC by hansjovis

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Fixes a bug where the schema block sidebar would not be correct after it had been added.

## Relevant technical choices:

* Used the `useSelect` WordPress React hook twice to make sure that the sidebar is re-rendered whenever:
	* The `schemaBlocksValidationResults` get updated.
	* The selected `blockInstance` gets updated.
* Without them, the sidebar would only be re-rendered when another block was selected.

## Test instructions

This PR can be tested by following these steps:

* 

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-04-01 09:36 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
> +type ClientIdValidation = Record<string, BlockValidationResult>;
nice

2021-04-01 09:50 UTC, increddibelly requested changes

2021-04-01 09:50 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> -export function innerBlocksSidebar( currentBlock: BlockInstance, options: InnerBlocksInstructionOptions ): ReactElement[] {
Waarom is deze class verwijderd? de Innerblocks class wordt al te groot en nu nog groter, terwijl de sidebar juist mooi is af te stoten naar een los component.

2021-04-01 10:59 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> -export function innerBlocksSidebar( currentBlock: BlockInstance, options: InnerBlocksInstructionOptions ): ReactElement[] {
Hij is in feite gerenamed naar `src/functions/presenters/InnerBlocksSidebar.tsx`.

Maar vanwege consistentie met de andere presenters zal ik hem hernoemen naar `InnerBlocksSidebarPresenter.tsx` 🙂 .

2021-04-06 06:43 UTC, increddibelly requested changes

2021-04-06 06:43 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +function useValidationResults( clientId: string ) {
```suggestion
function useValidationResults( clientId: string ) : typehint {
```

2021-04-06 06:43 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +function useBlock( clientId: string ) {
```suggestion
function useBlock( clientId: string ) : BlockInstance {
```

2021-04-06 06:43 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> + * @returns The latest version of the block.
```suggestion
 * @returns {BlockInstance} The latest version of the block.
```

2021-04-06 06:43 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +export function InnerBlocksSidebar( props: InnerBlocksSidebarProps ) {
zou je de filename nog even willen aanpassen? het is geen presenter meer.

2021-04-06 13:45 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> + * @returns The latest version of the block.
Decided together with Herre and the team to not supply type hints in the JSDocs, since TypeScript already supplies these hints.

2021-04-07 12:46 UTC, andizer requested changes
CR done.

2021-04-07 12:46 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
> +import { ReactElement } from "react";
Is there a reason that this line is moved downwards?

It isn't a big problem. Personally I would prefer having the external dependencies imported first.

2021-04-07 12:46 UTC, andizer commented on packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
> +export type ClientIdValidation = Record<string, BlockValidationResult>;
Ah nice 😄  , I've implemented this also in my PR #1146 and before that one it already lived somewhere else 😬

2021-04-07 12:46 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
> +			<ul className="yoast-block-sidebar-warnings"> { }
Is there a reason for the empty `{ }` ?

2021-04-07 12:46 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
> + * Creates a React element for a warning message
```suggestion
 * Creates a React element for a warning message.
```

2021-04-07 13:20 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
> +			<ul className="yoast-block-sidebar-warnings"> { }
No. I cut and pasted it from another class and did not notice that this was copied with it.

I will remove it.

2021-04-07 13:30 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
> +import { ReactElement } from "react";
I agree.

I think it would be best if we get together with the team (or even broader?) and define an import order.

I would even go as far as enforce it with an eslint rule. E.g. [I found this eslint plugin that we may use](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md).

2021-04-08 06:58 UTC, andizer commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
> +			<ul className="yoast-block-sidebar-warnings"> { }
You forgot to remove the `{ }`

```suggestion
			<ul className="yoast-block-sidebar-warnings">
```

2021-04-08 07:04 UTC, andizer approved these changes

2021-04-08 10:09 UTC, johannadevos commented
Acceptance: ✅ 

- [x] When Adding the Job Posting block, it is selected and I immediately see an up-to-date sidebar with a red bullet in the analysis saying that not all required blocks have been completed.
- [x] When I fill out all the required blocks, the analysis conclusion immediately becomes green.
- [ ] When entering the same job and post title, I only see the orange bullet point after a publish and refresh, but that's due to this known bug: https://yoast.atlassian.net/browse/P2-832
- [x] After the orange bullet point regarding the title has appeared, it is updated in real-time when I edit the job title.
- [x] Removing and re-instating a required block works as expected.

2021-04-08 10:10 UTC, merged