P2-775 Fixes some React keys in the schema blocks React components
Yoast/javascript pull request #1139
Opened 2021-04-01 07:24 UTC by hansjovis

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Fixes some key prop errors in some React components.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

* 

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-04-01 08:23 UTC, increddibelly requested changes

2021-04-01 08:23 UTC, increddibelly commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
> +		<li className="yoast-block-suggestion" key={ blockTitle }>
we want to be 100% unique, right?
```suggestion
		<li className="yoast-block-suggestion" key={ "BlockSuggestion" + blockTitle }>
```

2021-04-01 08:23 UTC, increddibelly commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
> +		<li className="yoast-block-suggestion yoast-block-suggestion--added" key={ blockTitle }>
```suggestion
		<li className="yoast-block-suggestion yoast-block-suggestion--added" key={ "BlockSuggestionAdded" + blockTitle }>
```

2021-04-01 08:23 UTC, increddibelly commented on packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
> +				key: "sidebar",
sidebar vind ik ook nog eng generiek; mss block name erbij? e.g.`job-postingsidebar`
```suggestion
				key: this.options.name + "Sidebar",
```

2021-04-01 08:23 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +		<li className="yoast-block-sidebar-warning" key={ warning }>
dan hebben toch alle warning elements dezelfde key? mss een parameter aan de functie toevoegen met block name of een number?

2021-04-02 10:12 UTC, hansjovis commented on packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
> +		<li className="yoast-block-sidebar-warning" key={ warning }>
Ik neem aan dat de warning message uniek is, doordat het bijvoorbeeld de block name bevat. Bijvoorbeeld `The ‘Job title’ block is required but missing.`.

2021-04-02 10:16 UTC, hansjovis commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
> +		<li className="yoast-block-suggestion" key={ blockTitle }>
[Keys hoeven niet globaal uniek te zijn](https://reactjs.org/docs/reconciliation.html#recursing-on-children):
> The key only has to be unique among its siblings, not globally unique.

Ik mis een whiteboard om het uit te leggen 😅, maar [de React documentatie legt het goed uit](https://reactjs.org/docs/reconciliation.html#recursing-on-children).

2021-04-02 14:40 UTC, increddibelly approved these changes

2021-04-02 14:57 UTC, merged