P2 786 only render ok when block is valid
Yoast/javascript pull request #1146
Opened 2021-04-07 08:31 UTC by andizer

## Summary

This PR can be summarized in the following changelog entry:

* [@yoast/schema-blocks] Shows the ok only when the added block suggestion hasn't any validation issues.

## Relevant technical choices:

* Decided to extra the `getValidationResult` function to its own helper because I had to duplicate its logic.

## Test instructions

This PR can be tested by following these steps:

* Adds the job block to your post
* See that for all block suggestions in the sidebare the `OK` value isn't rendered
* Fill in a value for each block and verify that `OK` is shown.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-04-07 09:37 UTC, hansjovis requested changes

2021-04-07 09:37 UTC, hansjovis commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
> + * @param {boolean} isValid    Is the added block valid.
I noticed yesterday that we as a team are inconsistent with adding or not adding type hints in the JSDoc for TypeScript files.

I asked Herre and the team during the pair session yesterday and we decided to remove the type hints, since we can rely on TypeScript giving the appropriate (and better) hints.

We do not have to get out of our way to remove them, however. But if it is not too much hassle: can you remove them from this file? 🙂

2021-04-07 09:37 UTC, hansjovis commented on packages/schema-blocks/src/blocks/BlockSuggestions.tsx
> +}
Also: If I am correct this code assumes that if the block type is valid, only one 'valid' result is known for this block type?

If so I think you can replace this with a `some` method:
```ts
return validationIssues.some( issue => issue.name === blockName && issue.isValid() );
```
or with the to-be-introduced `isValidResult` function:
```ts
return validationIssues.some( issue => issue.name === blockName && isValidResult( issue.result ) );
```

[The `some` array method checks if at least one of its elements passes the test implemented by the provided function.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) In this case: if at least one issue says that the block with `blockName` is valid.

2021-04-08 13:44 UTC, hansjovis approved these changes

2021-04-09 06:51 UTC, johannadevos commented
Acceptance: 🚧 

- [ ] When I add the Job Posting block, all the recommended blocks shown an `OK` although they are empty, as well as the Location block:

<img width="158" alt="Screenshot 2021-04-09 at 08 45 21" src="https://user-images.githubusercontent.com/20280513/114139931-ecb86a00-990f-11eb-8617-7fd84baddc54.png">

With regard to the Location block, I think you need the code from https://github.com/Yoast/javascript/pull/1142 / P2-807.

- [x] When I add text to the Job title and Job description, `OK` appears immediately, and disappears again when I remove the text.

@andizer Did you test your code again after pushing the latest changes?

2021-05-03 15:03 UTC, increddibelly commented
closed existing comments as this PR needs a thorough re-review.

2021-05-05 09:28 UTC, hansjovis requested changes

2021-05-05 09:28 UTC, hansjovis commented on packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
> +			const result = createAnalysisMessages( validations[ "1" ] );
This can be replaced by:
```ts
const validation = new BlockValidationResult( "1", "myBlock", BlockValidation.Valid, BlockPresence.Required );
const result = createAnalysisMessages( validation );
```
The `jest.mock( "@wordpress/data", ... );` and the `validations` variable at the top can be removed, since it is not used anymore.

2021-05-05 09:28 UTC, hansjovis commented on packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
> +			const result = createAnalysisMessages( validations[ "1" ] );
The other tests in this file will need to be adapted as well.

2021-05-05 09:32 UTC, hansjovis commented on packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
> +		const content: string = getBlockContent( blockInstance ) || "";
A block can contain more than the rich text field described by this block instruction. I'm not sure, but the `getBlockContent` could give a false positive, where it does not contain a value for the rich text (where the Schema is generated from) but does contain other (possible static?) HTML markup.

2021-05-06 09:32 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
> +export interface SuggestionsDto extends BlockSuggestionsProps {
Renamed to Props

2021-05-06 09:33 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
> + * @param parentBlockClientId The clientId of the target to add the block to.
title is the sidebar title, not the suggested block's title.

2021-05-06 09:35 UTC, increddibelly commented on packages/schema-blocks/src/core/Instruction.ts
> +			return null;
ok

2021-05-06 09:37 UTC, increddibelly commented on packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
> +			{ checkmark }
ooh that's nice. I was trying to remove logic from presentation, and this goes against that. Even though your suggestion is very easy to read.

2021-05-06 09:38 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
> +		const content: string = getBlockContent( blockInstance ) || "";
AFAIK this is the only way to get the block's current value during editing. THAT's the value we need to validate. I'm happy to be proved wrong; let's move this to the AR hour.

2021-05-06 09:43 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
> +		return new BlockValidationResult( blockInstance.clientId, this.options.name, validation, presence );
nope, that gives a message that we don't want to see.

2021-05-06 09:50 UTC, increddibelly commented on packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
> +			const result = createAnalysisMessages( validations[ "1" ] );
done

2021-05-06 09:54 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/Date.tsx
> +	}
this generates a sidebar message we don't want.

2021-05-06 09:57 UTC, increddibelly commented
> Acceptance: 🚧
> 
> * [x]  When I add the Job Posting block, all the recommended blocks shown an `OK` although they are empty, as well as the Location block:
> 
> <img alt="Screenshot 2021-04-09 at 08 45 21" width="158" src="https://user-images.githubusercontent.com/20280513/114139931-ecb86a00-990f-11eb-8617-7fd84baddc54.png">
> 
> With regard to the Location block, I think you need the code from #1142 / P2-807.
> 
> * [x]  When I add text to the Job title and Job description, `OK` appears immediately, and disappears again when I remove the text.
> 
> @andizer Did you test your code again after pushing the latest changes?

we have not yet fixed all of these; we'd have to add a validation method ( or use the `defaultValidation` function ) in each specific block's instruction code. As we're moving focus away from the job posting block to the to the bigger issue of UX and discovery of desired features, we will not be fixing them all _right now_ but only _as needed_ in the future.

2021-05-06 13:03 UTC, increddibelly commented on packages/schema-blocks/src/core/blocks/BlockInstruction.ts
>  	}
we set it in the template

2021-05-06 13:19 UTC, increddibelly commented on packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
> +		const content: string = getBlockContent( blockInstance ) || "";
thanks @hansjovis I'll follow your suggestion!

2021-05-06 15:00 UTC, hansjovis commented
CR: 👍 

* I did simplify [a couple of lines of code](https://github.com/Yoast/javascript/pull/1146/commits/0053d334d1321e04c8ef5e8fc606893a30eb64a1). (since we already check whether `isValid` is `true`, we do not the second check a few lines before).

2021-05-06 15:00 UTC, hansjovis approved these changes

2021-05-10 10:11 UTC, merged