Add duration block instruction
Yoast/javascript pull request #1190
Opened 2021-05-07 07:03 UTC by Xyfi

## Summary

This PR can be summarized in the following changelog entry:

* [schema-blocks] Added duration instruction.

## Relevant technical choices:

* Added `interpolate-components` package to for better internationalization.

## Test instructions

This PR can be tested by following these steps:

*

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2021-05-11 13:27 UTC, increddibelly requested changes

2021-05-11 13:27 UTC, increddibelly commented
CR ❔

2021-05-12 07:14 UTC, Xyfi commented on packages/schema-blocks/src/instructions/blocks/Duration.tsx
> +							placeholder="#"
<img width="118" alt="Screenshot 2021-05-12 at 09 14 25" src="https://user-images.githubusercontent.com/5389513/117933999-75a53580-b302-11eb-8a70-f45b647a5d83.png">

This is how the design looks, that's why I went for a `#`

2021-05-12 07:16 UTC, Xyfi commented on packages/schema-blocks/css/schema-blocks.css
> +	display: inline-block;
I have no control over the type of element, because this styling applies to the @wordpress/components TextControl component.

2021-05-12 09:15 UTC, Xyfi commented on package.json
> +    "build": "lerna run --ignore @yoast/content-analysis-app --ignore yoastseo build"
Being able to run `yarn build` from the root of the mono-repo, as explained in the technical decisions. I excluded the content-analysis-app and yoastseo, because their "build" is much more complex than just compiling the source-code.

2021-05-12 12:29 UTC, andizer requested changes
CR done

2021-05-12 12:29 UTC, andizer commented on packages/schema-blocks/css/schema-blocks.css
> +.wp-block-yoast-cooking-time .minutes-input {
I would move this class to free, because that is where we have a cooking time template.

2021-05-12 12:29 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/Duration.tsx
> +	private format: string = __( "%d minutes", "wordpress-seo" );
The textdomain should be yoast-schema-blocks

```suggestion
	private format: string = __( "%d minutes", "yoast-schema-blocks" );
```

2021-05-12 12:29 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/Duration.tsx
> +							aria-label={ __( "Cooking time", "wordpress-seo" ) }
Can you change the textdomain to yoast-schema-blocks
```suggestion
							aria-label={ __( "Cooking time", "yoast-schema-blocks" ) }
```

2021-05-12 12:29 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/Duration.tsx
> +				{ interpolateComponents( {
Is there a nicer way like React instead of interpolateComponents? I always find it hard to read.

As far as I can see this is happening:
```jsx
<div className="yoast-schema-flex">
	<TextControl
		type="number"
		placeholder="#"
		aria-label={ __( "Cooking time", "wordpress-seo" ) }
		className="minutes-input"
		onChange={ onChange }
		value={ props.attributes.value as number || "" }
	/>
    <p> { __( "minutes", 'yoast-schema-blocks' ) }</p> 
</div>
```

I just want to prevent having translatable strings like `{{input/}}{{p}} minutes{{/p}}`

2021-05-12 12:29 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/Duration.tsx
> +		/>;
We use a TextControl for the edit method, to keep things consistent I would just do: 

```suggestion
		return <p>{ sprintf( this.format, value ) }</p>;
```
```

2021-05-12 12:29 UTC, andizer commented on packages/schema-blocks/src/instructions/blocks/Duration.tsx
> +					mixedString: __( "{{input/}}{{p}} minutes{{/p}}", "wordpress-seo" ),
```suggestion
					mixedString: __( "{{input/}}{{p}} minutes{{/p}}", "yoast-schema-blocks" ),
```

2021-05-18 09:58 UTC, closed without merging

2021-05-18 09:59 UTC, Xyfi commented
Moved to the plugin.