P3-184 changes for zapier ui
Yoast/javascript pull request #878
Opened 2020-10-06 12:30 UTC by afercia

## Summary

This PR can be summarized in the following changelog entry:

[components] Add styles for the input field and button for the Zapier integration.

## Relevant technical choices:

To match the design for the Zapier integration the following adjustments and new styles are needed:
- The box-shadow of the button should be `box-shadow: inset 0 -2px 0 rgba(0, 0, 0, 0.1);`
- A grey background for the input field when it's readonly or disabled.
- A style variant to make the input label element not bold.
- Horizontal alignment of input field + button: the current CSS makes the input field full width so the button goes in a new line; we need styling to make the input + button horizontally aligned

Design to match:

<img width="652" alt="Screenshot 2020-10-06 at 11 41 30" src="https://user-images.githubusercontent.com/1682452/95201421-38af1880-07e0-11eb-8056-437d0f0c3ec2.png">

See https://yoast.atlassian.net/browse/P3-184

## Test instructions

This PR can be tested by following these steps:

- open the `packages/components/src/inputs/input.html` file in your browser and see the new examples

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * Zapier integration tab

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

See https://yoast.atlassian.net/browse/P3-184

2020-10-06 12:44 UTC, afercia commented
Note: for now, I kept the new styles strictly coupled to the specific usage for the Zapier design. For example the horizontal alignment takes in consideration only the specific case of an input field followed by a button. In the future, this could be improved to cover also other cases but for now we don't need anything else for Zapier.

2020-10-07 06:07 UTC, rolf-yoast requested changes

2020-10-07 06:07 UTC, rolf-yoast commented on packages/components/src/button/buttons.css
> +	box-shadow: inset 0 -2px 0 rgba(0, 0, 0, 0.1);
This is incorrect. This should stay 0.3. Only the secondary button should have 0.1

2020-10-07 06:25 UTC, rolf-yoast commented
CR 👍

2020-10-07 06:26 UTC, rolf-yoast approved these changes

2020-10-08 06:56 UTC, merged