Refactor the keyphraseDistribution research
Yoast/javascript pull request #888
Opened 2020-10-20 13:56 UTC by agnieszkaszuba

## Summary

This PR can be summarized in the following changelog entry:

* [yoastseo] Creates language-specific keyphraseDistribution researches

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

*

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2020-10-20 18:47 UTC, omarreiss commented on packages/yoastseo/src/languageProcessing/languages/de/researches/keyphraseDistribution.js
> +	return keyphraseDistributionResearcher( paper, researcher, functionWords );
You pass true or false everywhere else. Here you pass a list. Is this intentional?

2020-10-20 18:51 UTC, omarreiss commented on packages/yoastseo/src/languageProcessing/researches/base/keyphraseDistribution.js
> +const keyphraseDistributionResearcher = function( paper, researcher, funcWords ) {
`funcWords` implies an array. What would be a parameter name that describes the boolean well?

2020-10-20 18:54 UTC, omarreiss requested changes
Looking alright. Two things that need fixing.

2020-10-21 07:57 UTC, FAMarfuaty commented on packages/yoastseo/src/languageProcessing/languages/de/researches/keyphraseDistribution.js
> +	return keyphraseDistributionResearcher( paper, researcher, functionWords );
That wasn't intentional. We just fixed it.

2020-10-21 07:59 UTC, FAMarfuaty commented on packages/yoastseo/src/languageProcessing/researches/base/keyphraseDistribution.js
> +const keyphraseDistributionResearcher = function( paper, researcher, funcWords ) {
We changed it to `hasFunctionWords` in the latest commit

2020-10-21 09:54 UTC, merged