Add support for templates to inner blocks
Yoast/javascript pull request #944
Opened 2020-11-18 14:08 UTC by andizer

## Summary

This PR can be summarized in the following changelog entry:

* Adds the possiblity to define templates for each Innerblocks component.

## Relevant technical choices:

* Made some changes together with @herregroen. These changes will give the possibility to have nested arrays / objects and the combination of both.

## Test instructions

This PR can be tested by following these steps:

* Test this on `wordpress-seo`. Link the monorepo. In `src/schema-templates/recipe.block.php` add this to line 8:
```
template=[ [ "yoast/ingredients" ] ]
```
So it will look like this:
```
	{{inner-blocks allowed-blocks=[ "core/paragraph", "core/image", "yoast/ingredients" ] template=[ [ "yoast/ingredients" ] ] appender="button" appenderLabel="Add to recipe" }}

```
* Adds the recipe block to your post and see that the ingredients is added to it by default. This is because it defined in the template.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * Post edit -> The recipe block. Has not been released yet.

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [x] I have added unittests to verify the code works as intended

Fixes #

2020-11-18 15:37 UTC, hansjovis requested changes

2020-11-18 15:37 UTC, hansjovis commented on packages/schema-blocks/src/functions/process.ts
> +function processToken( tokens: IToken[] ): InstructionValue {
I would use the same method interface as `processBlockInstruction`, meaning that it would get a  `token` argument and an array of remaining `tokens`.

In my opinion it looks a bit cleaner when we consume the token in one place, instead of in multiple methods (`processToken`, `processArray` and `processObject`).

E.g.:
```js
function processToken( token: IToken, tokens: IToken[] ): InstructionValue {
	if ( token.isA( "array-open" ) ) {
		return processArray( tokens );
	}
	if ( token.isA( "object-open" ) ) {
		return processObject( tokens );
	}
	if ( token.isA( "empty-object" ) ) {
		return {};
	}
	if ( token.isA( "value" ) ) {
		return token.value as InstructionPrimitive;
	}
	throw "Invalid token found.";
}
```
Then in `processBlockInstruction` we would consume the token first, before processing it:
```js
const token = tokens.shift();
instruction.options[ key ] = processToken( token, tokens );
```
The first `tokens.shift()` in `processArray` and `processObject` should then be removed as well, since they are consumed in `processBlockInstruction` instead.

2020-11-18 15:37 UTC, hansjovis commented on packages/schema-blocks/tests/instructions/Innerblocks.test.ts
> +			1337,
Haha, nice 😛 .

2020-11-18 15:37 UTC, hansjovis commented on packages/schema-blocks/tests/functions/tokenize.test.ts
> +const testData = [
This test data takes up a large portion of the file (over 80%). It may be better to extract it into its own (JSON) file and import it here.

2020-11-18 15:37 UTC, hansjovis commented on packages/schema-blocks/tests/functions/tokenize.test.ts
> +	it( "extract a constant from the instruction", () => {
```suggestion
	it( "extracts a constant from the instruction", () => {
```

2020-11-18 15:37 UTC, hansjovis commented on packages/schema-blocks/tests/functions/tokenize.test.ts
> +	it( "extract a definition from the instruction", () => {
```suggestion
	it( "extracts a definition from the instruction", () => {
```

2020-11-19 06:58 UTC, andizer commented on packages/schema-blocks/src/core/Instruction.ts
> +export type InstructionObject = { [member: string]: InstructionValue };
I don't think so. If I use that syntax the editor tells me it will be circular.

2020-11-20 09:45 UTC, andizer commented on packages/schema-blocks/src/functions/process.ts
> +function processToken( tokens: IToken[] ): InstructionValue {
I have adapted your suggestion partially. I tried to shift the token and passing it in processToken, but that leads to unpredictable results: the tests is hanging because of an infinite loop.

For now I keep it as it is right now, because I can't oversee the consequences of the change and it is also out of scope for this issue. Feel free to create a ticket / PR to have this code structured the way you suggested.

2020-11-20 14:12 UTC, johannadevos commented
CR on the latest commits: ✅ 

Acceptance: 🚧 

Without adding `template=[ [ "yoast/ingredients" ] ]` to `recipe.block.php`, I can add the recipe block in my editor.
Once I add this code, I can no longer add the recipe block, and I see the following in the console:

<img width="865" alt="Screenshot 2020-11-20 at 15 10 48" src="https://user-images.githubusercontent.com/20280513/99809560-bfc31080-2b42-11eb-91e6-f957a8747455.png">

2020-11-24 15:27 UTC, johannadevos commented
Acceptance: ✅ 
Tested with Yoast/wordpress-seo#16397

2020-11-24 15:28 UTC, merged