P2 540 additional unit tests for p2 212
Yoast/javascript pull request #963
Opened 2020-12-08 08:33 UTC by increddibelly

## Summary

This PR can be summarized in the following changelog entry:

* Adds unit tests for InnerBlocks validation

## Relevant technical choices:

* I separated some concerns into classes e.g. `BlockDefinitionRepository` 
* the interface of the `valid()` method no longer accepts SaveProps or EditProps but takes a BlockInstance instead; this removes many dependencies on the gutenberg data models across the Instructions and Definitions.
* changed the `process` method to hide implementation details and remove more dependencies.

## Test instructions

This PR can be tested by following these steps:

* All affected code is covered directly by new or existing unit tests; this means that Travis has done our testing for us. There is currently no way to access this code from within a WordPress installation.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * 

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2020-12-08 14:35 UTC, johannadevos commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> + * Helper function to determine the urgency of an invalidation.
If this is a helper function, shouldn't it be placed in `innerBlocksHelper.ts`?

2020-12-08 14:36 UTC, johannadevos commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
>   * Helper function to create an invalid block.
If this is a helper function, shouldn't it be placed in `innerBlocksHelper.ts`?

2020-12-08 14:53 UTC, johannadevos commented
CR: ✅ with a few minor remarks.

* The changelog entry doesn't really correspond to the changes in the PR anymore. While it is not user-facing, it may be used by the plugin testers in the end, and it will end up on GitHub.
* I'm slightly surprised to see so many changes to the `yarn.lock`, is that all a consequence of bumping two packages in `package.json`?
* Two questions about helper functions.
* General remark: I did this CR by reading and clicking through the code, and I didn't notice anything that seemed strange to me. At the same time, it's hard (at least for me) to really oversee the functionality changes just by reading and clicking.
* But: Travis passes, so that means that acceptance is ✅

2020-12-08 16:44 UTC, hansjovis reviewed
First round of feedback. Will do the second round tomorrow.

2020-12-08 16:44 UTC, hansjovis commented on packages/schema-blocks/src/functions/innerBlocksHelper.ts
> +function getInnerblocksByName( blockInstance: BlockInstance, blockNames: string[] ): BlockInstance[] {
Proposition: replace this with a `filterBlocksRecursively` function that takes a callback function as a second argument instead. This should make it a lot more flexible and thus re-useable.

It could look something like this:
```ts
function getInnerblocksByName( blockInstance: BlockInstance, predicate: ( blockInstance: BlockInstance ): boolean ): BlockInstance[] {
	const foundBlocks: BlockInstance[] = [];

	recurseOverBlocks( blockInstance.innerBlocks, ( block: BlockInstance ) => {
		// Checks if the current block is one of the required types.
		if ( predicate( block ) ) {
			foundBlocks.push( block );
		}
	} );

	return foundBlocks;
}
```

2020-12-08 16:44 UTC, hansjovis commented on packages/schema-blocks/src/functions/innerBlocksHelper.ts
> +export { getInnerblocksByName };
The brackets are unnecessary here 🙂.
```suggestion
export getInnerblocksByName;
```

2020-12-08 16:44 UTC, hansjovis commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
>  		.forEach( block => onlyOneAllowed.push( block.name ) );
The `forEach` is not necessary here. The `filter` function already contains all the `onlyOneAllowed` blocks.
```suggestion
	onlyOneAllowed = requiredBlocks
		.filter( block => block.option === RequiredBlockOption.One );
```

2020-12-09 10:13 UTC, hansjovis commented
I think we are confounding two different concepts within the schema blocks: the concept of a **valid** block and the concept of a **missing** block.

A **valid** block is a block that has a value (and perhaps includes other validation steps in the future). This validation would power [the green check marks behind the block names in the schema analysis in the sidebar](https://www.sketch.com/s/ab6ebb5c-a390-434c-bdf1-8e3240cadcef/a/37RLrG).

A **missing** block is an inner block that is missing from the schema block. An inner block can be either required, recommended or optional.

2020-12-09 12:03 UTC, hansjovis commented
I thought long and hard about this, and I think the inner blocks validation can be made a lot simpler:
```js
function countRecursively( innerBlocks, predicate ) {
	const counts = countBy( innerBlocks, predicate );

	return innerBlocks.reduce(
		( prev, block ) => {
			const innerBlockCount = countRecursively( block.innerBlocks, predicate );
			return mergeWith( prev, innerBlockCount,
				( prevCount, addCount ) => {
					return prevCount + addCount;
				}
			);
		},
		counts
	);
}
```
```js
function valid( blockInstance ) {
	const innerBlocks = blockInstance.innerBlocks

	// Find the number of occurrences of each inner block recursively.
	const blockCounts = countRecursively( innerBlocks, block => block.name );

	const innerBlocksValidation = this.options.innerBlocksValidation;

	// Step 1: Check if the inner blocks occur the right amount of times.
	let invalid = Object.keys( innerBlocksValidation ).some(
		blockName => {
			if ( innerBlocksValidation[ blockName ].includes( 'required' ) ) {
				return ! ( blockName in blockCounts );
			}
			if ( innerBlocksValidation[ blockName ].includes( 'unique' ) ) {
				return blockCounts[ blockName ] > 1;
			}
			return false;
		}
	);

	// If it is already considered invalid, no need to do any further checking.
	if ( invalid ) {
		return false;
	}

	// Step 2: Check if every inner block (that has a definition) is valid according to its own validation.
	invalid = innerBlocks.some(
		innerBlock => {
			const blockDefinition = getBlockDefinition( innerBlock.name );

			if ( blockDefinition ) {
				return ! blockDefinition.valid( innerBlock );
			}
		}
	)

	return ! invalid;
}
```

2020-12-09 13:52 UTC, andizer requested changes
Cr done

2020-12-09 13:52 UTC, andizer commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +		name: name,
You can use `name` only because both key and value are the same.
```suggestion
	name,
```

2020-12-09 13:52 UTC, andizer commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +	}
Please use some newlines to make this more readable
```suggestion
	switch ( reason ) {
		case InvalidBlockReason.Optional: 
			return true;
		default: 
			return false;
	}
```

2020-12-11 08:44 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> + * Helper function to determine the urgency of an invalidation.
I split these classes on purpose : thisclass is purely about validation of innerblocks. Validation is another concern than manipulating innerblocks, which is what the innerblocksHelper does.

2020-12-11 08:45 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
>   * Helper function to create an invalid block.
see  https://github.com/Yoast/javascript/pull/963#discussion_r540781410

2020-12-11 08:45 UTC, increddibelly commented on packages/schema-blocks/src/functions/innerBlocksHelper.ts
> +function getInnerblocksByName( blockInstance: BlockInstance, blockNames: string[] ): BlockInstance[] {
that's a really nice idea.

2020-12-11 14:38 UTC, increddibelly commented on packages/schema-blocks/src/functions/innerBlocksHelper.ts
> +function getInnerblocksByName( blockInstance: BlockInstance, blockNames: string[] ): BlockInstance[] {
done

2020-12-15 08:39 UTC, hansjovis approved these changes
Code review comments from the first round of feedback have been resolved, so I am giving my OK.

2020-12-15 09:31 UTC, johannadevos commented
Merging this PR, because CR was ✅ and no acceptance test is required.

2020-12-15 09:31 UTC, merged