Add unit tests for periphrastic passive voice helper files
Yoast/javascript pull request #965
Opened 2020-12-08 15:04 UTC by FAMarfuaty

## Summary

This PR can be summarized in the following changelog entry:

* [yoastseo] Creates a new passiveVoice/periphrastic folder in yoastseo/spec/languageProcessing/helpers and adds the spec files for periphrastic helpers there. Also improves code styles of the periphrastic helper files and Dutch `getParticiple` helper file.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

*

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #https://yoast.atlassian.net/browse/LINGO-564

2021-01-06 15:41 UTC, manuelaugustin requested changes
CR 🚧

Looks great overall! There just were a few small points, see comments.

2021-01-06 15:41 UTC, manuelaugustin commented on packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getSentencePartsSpec.js
> +		const sentence = "The English are always throwing parties.";
The description says that sentence parts without auxiliary are filtered out. However, specs only test whether there is a sentence part. It doesn't say anything about whether a sentence part is filtered when it's not passive. For that, you'd have to check something like:
`expect( getSentenceParts( sentence, options1 )[ 0 ].isPassive() ).toBe( false );`

2021-01-06 15:41 UTC, manuelaugustin commented on packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getSentencePartsSpec.js
> +	it( "returns the sentence parts that are passive", function() {
Also here it's good to check that the sentence part returned is actually passive.

2021-01-11 09:48 UTC, FAMarfuaty commented
@manuelaugustin I've adjusted the specs based on your suggestion.

2021-01-15 16:16 UTC, manuelaugustin commented
CR2 👍

2021-01-15 16:16 UTC, merged