P1 228 add ert to insights modal
Yoast/javascript pull request #978
Opened 2020-12-16 11:18 UTC by JoseeWouters

## Summary

This PR can be summarized in the following changelog entry:

* Adds an InsightCard component to be used for the Estimated Reading time in the Insight modal

## Relevant technical choices:

* Adds InsightCard component for the Insight modal

## Test instructions

This PR can be tested by following these steps:

* See test instructions for [the corresponding branch on Premium](https://github.com/Yoast/wordpress-seo-premium/pull/3121)

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes P1-228

2020-12-21 10:07 UTC, maartenleenders requested changes
CR 🚧 

I think there are some suboptimal compositions here, I'd be happy to help fix them.

2020-12-21 10:07 UTC, maartenleenders commented on packages/components/src/WordOccurrenceInsights.js
> +	const header = <p className="yoast-field-group__title">{ getHeader() }</p>;
I think here as well, in stead of adding a title here, we could wrap the WordOccurrences in a `FieldGroup`. In fact, I think we could do some refactoring to wrap the `DataModel` in a `FieldGroup`, although I seem to remember there was some reason for us to keep using the `WordOccurrences`. 

I'd be happy to help with this.

2020-12-21 19:50 UTC, JoseeWouters commented on packages/components/src/InsightsCard.js
> +					<div className="yoast-insights-card__description">{ this.getDescription() }</div>
Clean solution, thanks! Can you explain what exactly this code does?

2020-12-21 19:53 UTC, JoseeWouters commented on packages/components/src/WordOccurrenceInsights.js
> +	const header = <p className="yoast-field-group__title">{ getHeader() }</p>;
Ok, let's discuss this 👍

2020-12-22 14:56 UTC, maartenleenders approved these changes

2020-12-23 13:47 UTC, merged