P2 281 add schema validation to the store
Yoast/javascript pull request #992
Opened 2020-12-28 15:33 UTC by increddibelly

## Summary

This PR can be summarized in the following changelog entry:

* Stores the block validation result in the editor store.

## Relevant technical choices:

* changed the validation interface to return an array of validationresults (clientId / name / result)
* changed the validation of innerblocks to correctly identify the valid and invalid cases of required and optional inner blocks.

## Test instructions

This PR can be tested by following these steps:

* Create a Post.
* add a Job Posting (not available at this time)
* open the browser console (F12)
* (testcase A)remove a required block (e.g. job title)
* this should trigger validation, and that should cause validation to be stored in the wordpress store.
* the console shows you what is sent to the store, and you match it with what you see on-screen. Storing a validation will log an object to the console, with the following properties:
```
name: the block type (e.g. job-title)
clientId: a random guid, a generated id on the web page
result: a code, indicating the validation result:
	Unknown = -2, // a block we can't validate; e.g. a third party block.
	Optional = -1, // doesn't matter if this block is invalid
	Valid = 0, // yay
	Missing = 1, // when removing a required block
	TooMany = 2, // when adding a singleton block more than once e.g. 2x Job Title
```
* (testcase B) add the job title back; validation should trigger and it should be happy now (code 0)
* (testcase C) add another job title to the post; this is illegal and may not (should not) even be possible. The validation object in the console should now read TooMany (2) for the block with name "job-title".

Note that these logs will be removed once the "jobs" schema block is ready for release. For now, let's enjoy the information they provide :-)

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * this PR is behind the schema-blocks feature toggle, which is off. no effect should be noticable when creating a new post, unless the feature is on.

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #

2020-12-29 11:15 UTC, andizer requested changes
Cr done 

You've added an empty file: `packages/schema-blocks/src/redux/selectors/blockValid.js` - Is this done by accident?

2020-12-29 13:00 UTC, increddibelly commented on packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
> +		console.log( blockValidation );
yes it is, see test instructions :-) for now, this is a very easy helper for our QA team to see what's going on; we already have tickets in place to remove console.logs before release.

2020-12-29 13:01 UTC, increddibelly commented on packages/schema-blocks/src/functions/gutenberg/watch.ts
> +			console.log( "unable to validatie block of type [" + block.name + "] " + block.clientId );
good catch!

2020-12-30 09:55 UTC, hansjovis requested changes
I have some remarks on the code 😅 . If you want we can walk through them together.

I would also adapt the test instructions. Right now it tests whether the values are correct _before_ we set it on the store. We want to test whether it _is_ actually on the store.

We can use the Redux dev-tools browser extension for this. Or we can do it manually in the browser's console.

2020-12-30 09:55 UTC, hansjovis commented on packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
> +		dispatch( "yoast-seo/editor" ).setBlockValidation( blockValidation.clientId, blockValidation.result );
Also: how much value do we want to put on keeping the `schema-blocks` package a package than can be reused? 

Right now this line makes the package dependent on having a store named `yoast-seo/editor` in your WordPress editor.

2020-12-30 09:55 UTC, hansjovis commented on packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
> +		dispatch( "yoast-seo/editor" ).setBlockValidation( blockValidation.clientId, blockValidation.result );
> If we want to use the setBlockValidation this way, we first need to register it as an action on the yoast-seo/editor store.

FYI: @johannadevos and I tried to do that in the plugin before you took over. However, we could not get the import of the action to work...

2020-12-30 09:55 UTC, hansjovis commented on packages/schema-blocks/src/redux/reducers/schemaBlocksReducer.js
> +}
My guess is that this reducer does not give the results we want.

I would implement it like this:
```js
const initialState = {};

export function schemaBlocksReducer( state = initialState, action ) {
	switch ( action.type ) {
		case SET_BLOCK_VALID: {
			const validationResult = { [ action.clientId ]: action.validation };
			// Make a shallow copy of the state and overwrite the validation result of the block.
			return Object.assign( {}, state, validationResult );
		}
		default: {
			return state;
		}
	}
}
```

This would give a state that maps clientIds to a validation result:
```json
{
	"1234-abcd": -2,
	"5432-wxyz": 0,
}
```

2020-12-30 09:55 UTC, hansjovis commented on packages/schema-blocks/src/redux/reducers/schemaBlocksReducer.js
> +}
If we want it more readable inside of the store, we can opt for using the `BlockValidation` enum labels instead. By using the reverse mapping that TypeScript creates automatically:
```js
const validationResult = { [ action.clientId ]: BlockValidation[ action.validation ] };
```
Result:
```json
{ "1234-abcd": "TooMany" }
```

2020-12-31 07:34 UTC, increddibelly commented on packages/schema-blocks/src/core/Instruction.ts
>  	 * @returns `true` if the instruction block is valid, `false` if the block contains errors.
good point, I haven't covered the watch script at all.

2020-12-31 07:37 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
> +			return false;
this is likely to grow. but you're right, we don't need this now

2020-12-31 07:42 UTC, increddibelly commented on packages/schema-blocks/src/functions/gutenberg/watch.ts
> +		}
this deals with third party blocks. Also, it took me quite a while to find out that missing block registrations were the reason my tests weren't working; during development of the epic this else should be very helpful!

2020-12-31 07:43 UTC, increddibelly commented on packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
>  	const onlyOneAllowed = requiredBlocks.filter( block => block.option === RequiredBlockOption.One );
I'll have a look, this seems unintentional

2020-12-31 08:40 UTC, increddibelly commented on packages/schema-blocks/src/core/validation/BlockValidation.ts
> +	Optional = -1,
I'm going to keep it. We will need this for optional blocks that are invalid; we can add the optional validation to the output array.

2020-12-31 09:47 UTC, increddibelly commented on packages/schema-blocks/src/redux/reducers/schemaBlocksReducer.js
> +}
we need an array of BlockValidations, I think we'll need a bit more work here.

2021-01-05 09:42 UTC, Xyfi commented
CR 👍

2021-01-05 14:56 UTC, hansjovis commented
Acceptance test: 🚫 

> The validation object in the console should now read TooMany (2) for the block with name "job-title".

I do get a `TooMany` validation result when multiple job titles are added. However, this result is on the job posting block itself. The individual job title blocks are considered valid.

The same happens when only one job title block is there. The job posting block itself gets a result of `Missing`. Though there is evidently no job title block anymore to tie the validation result too 🤔.

2021-01-07 10:14 UTC, increddibelly commented
Validation is complicated but I tried to make sense:
- when a required block is missing, it has no Id, so we can't flag the missing block. Instead, we make the parent block invalid because it is missing a required part.
- when a singleton block is present more than once, both blocks can be either valid or invalid _for their own reasons_, but the parent block is invalid because it has too many things of type xyz. We should specify the type here, and I think that was missing until we started working on it this morning.
- when all of the blocks in an innerblocks block are valid, the innerblocks block is valid.

2021-01-20 10:42 UTC, hansjovis requested changes
Some documentation changes and a question about a casting to `unknown` in the `SchemaDefinition`.

2021-01-20 10:42 UTC, hansjovis commented on packages/schema-blocks/src/core/schema/SchemaDefinition.ts
> +		const configuration = this.configuration() as unknown as SchemaDefinitionConfiguration;
This effectively cancels out any type checks by TypeScript. What is the reason behind this change? 🙂

2021-01-20 10:42 UTC, hansjovis commented on packages/schema-blocks/src/core/validation/BlockValidation.ts
> +}
I would add documentation to each value, to indicate when this value is and/or should be used. Since this is an integral part of block validation, it should be absolutely clear to the developer what the possible values mean.

E.g.:
```js
/**
 * The result of validating a block.
 */
export enum BlockValidation {
	/**
	 * Block validation has been skipped.
	 */
	Skipped = -2,
	/**
	 * The block can't be validated.
	 */
	Unknown = -1,
	/**
	 * The block is valid.
	 */
	Valid = 0,
	/**
	 * The block is invalid.
	 */
	Invalid = 1,
	/**
	 * ...
	 */
	MissingAttribute = 2,
	MissingBlock = 3,
	TooMany = 4,
}
```

2021-01-20 10:42 UTC, hansjovis commented on packages/schema-blocks/src/functions/validators/validateMany.ts
> + * @param results    The name of the attribute to check.
```suggestion
```
The function does not have this parameter anymore.

2021-01-21 08:51 UTC, increddibelly commented
> We want to test whether it _is_ actually on the store.
> We can use the Redux dev-tools browser extension for this. Or we can do it manually in the browser's console.

I think I've already mentioned both these paths in the instructions? should I clarify my instructions?

2021-01-21 09:22 UTC, increddibelly commented on packages/schema-blocks/src/core/schema/SchemaDefinition.ts
> +		const configuration = this.configuration() as unknown as SchemaDefinitionConfiguration;
this was needed during dev - it isn't anymore. I guess I have fixed the return type by now. Well spotted!

2021-01-21 09:25 UTC, increddibelly commented on packages/schema-blocks/src/core/Definition.ts
> +			console.log( "validating " + instruction.options.name + " against " + blockInstance.name + " => " + BlockValidation[ issue.result ] );
and enable / disable in one step. I've been juggling this idea in my head too, I feel this logging is too valuable to discard entirely.

2021-01-22 14:26 UTC, hansjovis commented on packages/schema-blocks/src/core/Definition.ts
> +			console.log( "validating " + instruction.options.name + " against " + blockInstance.name + " => " + BlockValidation[ issue.result ] );
I agree, since the package is still full on in development keeping these log statements are fine until we have some kind of logger implemented.

2021-01-22 14:27 UTC, hansjovis commented
> I think I've already mentioned both these paths in the instructions? should I clarify my instructions?

No, the current test instructions are fine 🙂.

2021-01-22 14:29 UTC, hansjovis approved these changes

2021-01-22 15:44 UTC, hansjovis commented
Acceptance test: ✅

2021-01-22 15:44 UTC, merged