Create ImageSelect component
Yoast/javascript pull request #997
Opened 2021-01-05 20:03 UTC by JoseeWouters

## Summary

This PR can be summarized in the following changelog entry:

* Adds an ImageSelect component with an image preview or url preview

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

* Run `yarn start` in `apps/components`
* Go to image select
* When clicked on the image preview or "select image" button, a placeholder image should appear
* Make sure you can also remove the image by clicking "remove image" button
* In ImageSelectWrapper.js change `hasPreview` to `false` and you should now see a disabled input field
* With an image selected, this input field should show the url of the image

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes P1-187

2021-01-07 07:44 UTC, igorschoester requested changes
CR 🏗️ 

Besides the code comments: the tests are missing 😅

2021-01-07 07:44 UTC, igorschoester commented on apps/components/ImageSelectWrapper.js
> +					hasPreview={ false }
Maybe add another ImageSelect that has `hasPreview` true? Or a toggle so you can switch between?

2021-01-07 07:44 UTC, igorschoester commented on packages/components/src/image-select/ImageSelect.js
> +	onClick: () => {},
```suggestion
	onClick: PropTypes.func,
```

2021-01-07 07:44 UTC, igorschoester commented on packages/components/src/image-select/ImageSelect.js
> +		const imageSelectButtonsProps = this.props;
I think it is better to specify which props are for the ImageSelectButtons exactly. It makes it transparent and it will prevent unintentional extra props like `ImageAltText` from being passed on.
Also the IDs and `onRemoveImageClick` are missing from the ImageSelect props.

2021-01-07 07:44 UTC, igorschoester commented on packages/components/src/image-select/ImageSelect.js
> +class ImageSelect extends React.Component {
Because this component has no complex features (even state doesn't count anymore with hooks 😄 ), it would be nice if this was a function instead of a class.

2021-01-07 09:54 UTC, JoseeWouters commented on packages/components/src/image-select/ImageSelect.js
> +		const imageClassName = this.props.imageSelected
imageSelected prop exists already and eslint doesn't allow a negated condition. Therefore keeping it like this.

2021-01-07 10:31 UTC, JoseeWouters commented on apps/components/ImageSelectWrapper.js
> +					hasPreview={ false }
Made a toggle, great idea!

2021-01-07 14:14 UTC, marijnyoast approved these changes
CR 👍🏻

2021-01-08 14:32 UTC, maartenleenders commented
I fixed the snapshots, but they are caused by the inclusion of the `TextInput`, which I believe is not necessary for this PR:

@JoseeWouters Is there a decision anywhere about showing the disabled input URL when the preview is hidden?

If not, I believe you may have misunderstood my intention when I said "make the preview conditional". 

My intention was not to bring back the disabled URL input when the preview is hidden, but to either have "only buttons", or "buttons and preview". I believe the agreement was that everywhere where there is an image select + input field now (e.g. settings, social previews in free) we will eventually have that preview variant you made.

In the case of premium, social previews have "their own preview", so we only need the `ImageSelectButtons`.

So perhaps what we actually want is to export the `ImageSelectButtons` (as you have), and a `ImageSelect` that always has a preview. No booleans required, and no chance of accidentally putting "hidden premium code" in free, which is a faux-pas.

I'd be happy to help out with implementing that.

2021-01-11 10:51 UTC, maartenleenders commented
Moved to implement the new `ImageSelect` in the Social Previews here: https://github.com/Yoast/javascript/tree/use-new-image-select-in-social-preview-form  but needs some more work later.

2021-01-11 15:43 UTC, maartenleenders commented
Acc ✅

2021-01-11 15:43 UTC, merged